
package compshop;

import java.awt.HeadlessException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.regex.*;
import javax.swing.JOptionPane;

public class Accessories extends javax.swing.JFrame {

        public Accessories() {
        initComponents();
        
        jbtndelete.setEnabled(false);
        jbtnmodify.setEnabled(false);

        setTitle("Computer Shopee Management System");
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");

            String sql = "select * from accessories ";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            //pstmt.setInt(1,Integer.parseInt(isbn.getText()));

            ResultSet rs = pstmt.executeQuery();
           while(rs.next())
            {
                String name = rs.getString("Name");
               

            }
         conn.close();

        }catch(ClassNotFoundException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jbtnadd = new javax.swing.JButton();
        jbtnmodify = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jbtndisplay = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ltitle = new javax.swing.JLabel();
        lprice = new javax.swing.JLabel();
        lcopies = new javax.swing.JLabel();
        copies = new javax.swing.JTextField();
        jbtnsearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lisbn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        image.setFont(new java.awt.Font("18thCentury", 1, 14)); // NOI18N
        image.setForeground(new java.awt.Color(255, 255, 255));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pruthviraj Deshmukh\\Desktop\\Software\\Computer Shopee\\src\\images\\url.jpg")); // NOI18N
        image.setLabelFor(image);

        setDefaultCloseOperation(0);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 200, 110, 44);

        isbn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });
        isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isbnKeyReleased(evt);
            }
        });
        jPanel1.add(isbn);
        isbn.setBounds(170, 140, 190, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 360, 160, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 280, 210, 50);

        title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleKeyReleased(evt);
            }
        });
        jPanel1.add(title);
        title.setBounds(170, 210, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 290, 142, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 70, 44);

        price.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(190, 290, 130, 30);

        jbtnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnadd.setText("Add");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnadd);
        jbtnadd.setBounds(80, 490, 100, 30);

        jbtnmodify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnmodify.setText("Modify");
        jbtnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodifyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmodify);
        jbtnmodify.setBounds(220, 490, 100, 30);

        jbtndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndelete);
        jbtndelete.setBounds(350, 490, 110, 30);

        jbtndisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndisplay.setText("Display");
        jbtndisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndisplayActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndisplay);
        jbtndisplay.setBounds(490, 490, 110, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(620, 490, 90, 30);

        ltitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ltitle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ltitle);
        ltitle.setBounds(360, 210, 90, 30);

        lprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lprice.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(lprice);
        lprice.setBounds(330, 290, 120, 30);

        lcopies.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lcopies.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lcopies);
        lcopies.setBounds(300, 370, 140, 30);

        copies.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        copies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiesActionPerformed(evt);
            }
        });
        copies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                copiesKeyReleased(evt);
            }
        });
        jPanel1.add(copies);
        copies.setBounds(190, 370, 110, 30);

        jbtnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsearch.setText("Search");
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsearch);
        jbtnsearch.setBounds(450, 140, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Accessories");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(278, 0, 292, 60);
        jPanel1.add(pid);
        pid.setBounds(480, 470, 0, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pruthviraj Deshmukh\\Desktop\\Software\\Computer Shopee\\src\\images\\url.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 0, 970, 530);

        lisbn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lisbn);
        lisbn.setBounds(360, 140, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter 1-4 digit ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 170, 180, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
        // TODO add your handling code here:
        jbtndisplay.setEnabled(true);
        jbtnadd.setEnabled(false);
        jbtndelete.setEnabled(true);
        jbtnmodify.setEnabled(true);

        try{
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","")) {
                String sql = "select * from accessories where id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(isbn.getText()));

                ResultSet rs = pstmt.executeQuery();
                if(rs.next())
                {
                    //C_id.setText(rs.getString("c_id"));
                    title.setText(rs.getString("Name"));
                    copies.setText(rs.getString("Quantity"));
                    price.setText(rs.getString("Amount"));
                    //jComboBox1.setText(rs.getString("pid"));
                    //jComboBox1.(rs.getSelectedItem("pid");
                        //title.setText(rs.getString("title"));
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null," Record not found");
                    }    }

                }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_jbtnsearchActionPerformed

    private void copiesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_copiesKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{0,100}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(copies.getText());
        if(!match.matches()) {
            lcopies.setText("Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
            lcopies.setText(null);
            jbtnadd.setEnabled(true);
            //jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_copiesKeyReleased

    private void copiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copiesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.hide();
        login_s frm=new login_s();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbtndisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndisplayActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Accdisplay().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtndisplayActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        // TODO add your handling code here:
        jbtnadd.setEnabled(false);
        jbtnmodify.setEnabled(false);
        jbtndisplay.setEnabled(true);

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");

            String sql = "delete from accessories where id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setInt(1,Integer.parseInt(isbn.getText()));
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Deleted Succesfully");
           // C_id.setText("");
            isbn.setText("");
            title.setText("");
            price.setText("");
            copies.setText("");

            conn.close();

        }catch(   HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        }

        /**
        * @param args the command line arguments
        */
        public static void main(String args[]) {
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
                new Accessories().setVisible(true);
            }
        );

    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jbtnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodifyActionPerformed
        // TODO add your handling code here:
        jbtnadd.setEnabled(false);
        jbtndelete.setEnabled(false);
        jbtndisplay.setEnabled(true);

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");

            String sql = "update accessories set  Name = ?,  Amount= ?, Quantity = ? where id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
           //pstmt.setInt(1,Integer.parseInt(C_id.getText()));
            pstmt.setString(1, title.getText());
            pstmt.setInt(2,Integer.parseInt(price.getText()));
            pstmt.setInt(3,Integer.parseInt(copies.getText()));
            pstmt.setInt(4,Integer.parseInt(isbn.getText()));

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Modified");
            //C_id.setText("");
            isbn.setText("");
            title.setText("");
            price.setText("");
            copies.setText("");
            conn.close();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jbtnmodifyActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        // TODO add your handling code here:
        jbtndelete.setEnabled(false);
        jbtnmodify.setEnabled(false);
        //String c_Id = C_id.getText();
        String Id = isbn.getText();
        String Name=title.getText();
        String Amount=price.getText();
        String Quantity=copies.getText();

        /*if(c_Id.equals("")){
            JOptionPane.showMessageDialog(null," Customer Id is Mandatory .");
        }*/
        if(Id.equals("")){
            JOptionPane.showMessageDialog(null," Id is Mandatory .");
        }
        if(Name.equals("")){
            JOptionPane.showMessageDialog(null," Name is Mandatory .");
        }
        if(Amount.equals("")){
            JOptionPane.showMessageDialog(null," Amount  is Mandatory .");
        }
        if(Quantity.equals("")){
            JOptionPane.showMessageDialog(null," Quantity is Mandatory .");
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");

            String sql = "insert into accessories values(?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
           // pstmt.setInt(1,Integer.parseInt(C_id.getText()));
            pstmt.setInt(1,Integer.parseInt(isbn.getText()));
            pstmt.setString(2, title.getText());
            pstmt.setInt(3,Integer.parseInt(price.getText()));
            pstmt.setInt(4,Integer.parseInt(copies.getText()));

            //String value=jComboBox1.getSelectedItem().toString();
            //pstmt.setString(8, value);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Inserted");
            //C_id.setText("");
            isbn.setText("");
            title.setText("");
            price.setText("");
            copies.setText("");
            conn.close();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jbtnaddActionPerformed

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(price.getText());
        if(!match.matches()) {
            lprice.setText("Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
            lprice.setText(null);
            jbtnadd.setEnabled(true);
            //jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_priceKeyReleased

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void titleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z ]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(title.getText());
        if(!match.matches()) {
            ltitle.setText("Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
            ltitle.setText(null);
            jbtnadd.setEnabled(true);
            //jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_titleKeyReleased

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void isbnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(isbn.getText());
        if(!match.matches()) {
            lisbn.setText("Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
            lisbn.setText(null);
            jbtnadd.setEnabled(true);
            jbtnmodify.setEnabled(true);
        }

    }//GEN-LAST:event_isbnKeyReleased

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField copies;
    private javax.swing.JLabel image;
    private javax.swing.JTextField isbn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtndisplay;
    private javax.swing.JButton jbtnmodify;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JLabel lcopies;
    private javax.swing.JLabel lisbn;
    private javax.swing.JLabel lprice;
    private javax.swing.JLabel ltitle;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField price;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
