/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compshop;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.util.regex.*;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Somnath
 */
public class Bill extends javax.swing.JFrame {

    DefaultTableModel model;
    
     public Bill() {
        initComponents();
        //showDate();
        setTitle("Computer Shopee Managemant System");
       // qtotal.setVisible(true);
        
        model = new DefaultTableModel();
        jTable1.setModel(model);
       // model.addColumn("SR.");
        model.addColumn("id");
        model.addColumn("Name");
        model.addColumn("Amount");
        model.addColumn("Quantity");
        model.addColumn("tot_cost");
    /**
     * Creates new form Publisher_Details
     */
   
        Date obj=new date();
        SimpleDateFormat df= new SimpleDateFormat("YYYY-MM-DD");
        String date=obj.toString();
        
        Expiry_date.setText(df.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        C_id = new javax.swing.JTextField();
        jbtnadd = new javax.swing.JButton();
        jbtndisplay = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Expiry_date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pay_method = new javax.swing.JComboBox<>();
        lname = new javax.swing.JLabel();
        lid = new javax.swing.JLabel();
        lexp = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a_id = new javax.swing.JTextField();
        amt = new javax.swing.JTextField();
        cost = new javax.swing.JButton();
        copies = new javax.swing.JLabel();
        laid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totall = new javax.swing.JButton();
        ltotal = new javax.swing.JTextField();
        etotal = new javax.swing.JLabel();
        qtotal = new javax.swing.JLabel();
        tquant = new javax.swing.JLabel();
        aname = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();

        image.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        image.setForeground(new java.awt.Color(255, 255, 255));
        image.setText("Expiry Date");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 80, 60, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Customer ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 140, 130, 40);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(160, 90, 100, 40);

        C_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_idActionPerformed(evt);
            }
        });
        C_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                C_idKeyReleased(evt);
            }
        });
        jPanel1.add(C_id);
        C_id.setBounds(160, 140, 100, 40);

        jbtnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnadd.setText("Add");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnadd);
        jbtnadd.setBounds(660, 360, 120, 30);

        jbtndisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndisplay.setText("Generate Bill");
        jbtndisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndisplayActionPerformed(evt);
            }
        });
        jbtndisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbtndisplayKeyReleased(evt);
            }
        });
        jPanel1.add(jbtndisplay);
        jbtndisplay.setBounds(590, 510, 150, 30);

        jbtnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnback.setText("Back");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback);
        jbtnback.setBounds(800, 510, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Bill Details");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 10, 300, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 220, 120, 50);

        Expiry_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Expiry_dateActionPerformed(evt);
            }
        });
        Expiry_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Expiry_dateKeyReleased(evt);
            }
        });
        jPanel1.add(Expiry_date);
        Expiry_date.setBounds(160, 230, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Payment ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 300, 130, 60);

        pay_method.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pay_method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHEQUE", "CARD" }));
        pay_method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_methodActionPerformed(evt);
            }
        });
        pay_method.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_methodKeyReleased(evt);
            }
        });
        jPanel1.add(pay_method);
        pay_method.setBounds(150, 330, 110, 40);

        lname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lname);
        lname.setBounds(280, 140, 80, 40);
        jPanel1.add(lid);
        lid.setBounds(270, 90, 60, 40);

        lexp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lexp);
        lexp.setBounds(290, 270, 90, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 380, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Amount");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(660, 210, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(660, 260, 103, 30);

        quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantActionPerformed(evt);
            }
        });
        quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantKeyReleased(evt);
            }
        });
        jPanel1.add(quant);
        quant.setBounds(790, 260, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Accessories Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 160, 220, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Accessories ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(630, 100, 145, 40);

        a_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_idActionPerformed(evt);
            }
        });
        a_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a_idKeyReleased(evt);
            }
        });
        jPanel1.add(a_id);
        a_id.setBounds(790, 100, 60, 40);

        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });
        jPanel1.add(amt);
        amt.setBounds(790, 310, 80, 30);

        cost.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cost.setText("Cost");
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        jPanel1.add(cost);
        cost.setBounds(660, 310, 100, 30);
        jPanel1.add(copies);
        copies.setBounds(90, 530, 0, 30);
        jPanel1.add(laid);
        laid.setBounds(850, 100, 80, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("ID");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 180, 30, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("ID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(680, 120, 30, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Method");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 350, 100, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 420, 452, 130);

        totall.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totall.setText("Total");
        totall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totallActionPerformed(evt);
            }
        });
        jPanel1.add(totall);
        totall.setBounds(670, 420, 90, 30);

        ltotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltotalActionPerformed(evt);
            }
        });
        jPanel1.add(ltotal);
        ltotal.setBounds(800, 420, 80, 30);
        jPanel1.add(etotal);
        etotal.setBounds(490, 520, 0, 0);
        jPanel1.add(qtotal);
        qtotal.setBounds(470, 540, 0, 0);
        jPanel1.add(tquant);
        tquant.setBounds(500, 530, 10, 0);
        jPanel1.add(aname);
        aname.setBounds(790, 170, 80, 30);
        jPanel1.add(amount);
        amount.setBounds(790, 210, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void C_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_idActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_C_idActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        // TODO add your handling code here:
        
         // jbtndelete.setEnabled(false);  
  // jbtnmodify.setEnabled(false);
       model.addRow(new Object[]{
          //jComboBox1.getSelectedItem(),
          id.getText(),
          aname.getText(),
          amount.getText(),
          quant.getText(),
          amt.getText()
      });
      
     try{
 
            Class.forName("com.mysql.jdbc.Driver");
                      Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");

            
            
           // CallableStatement cs = conn.prepareCall("{ call stock1(?,?)}");
            //String val=jComboBox1.getSelectedItem().toString();
        
            //cs.setInt(1,Integer.parseInt(quant.getText()));
            //cs.setInt(2,Integer.parseInt(a_id.getText()));
            
            //cs.executeUpdate();
     
           
        }catch(ClassNotFoundException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        } 
           
        String ID=id.getText();
          String Name=C_id.getText();
           jTextField1.setText(pay_method.getSelectedItem().toString());
          String Pay=jTextField1.getText();
             // String Address=address.getText();
               // String PhoneNo=phone.getText();
              String Expiry=Expiry_date.getText();
               if(ID.equals("")){
                   JOptionPane.showMessageDialog(null," id is Mandatory .");
               }
                if(Name.equals("")){
                   JOptionPane.showMessageDialog(null," name is Mandatory .");
                }
                /*if(Expiry.equals("")){
                   JOptionPane.showMessageDialog(null," Expiry is Mandatory .");
                } */
                 if(Pay.equals("")){
                   JOptionPane.showMessageDialog(null," Payment method is Mandatory .");
                }  
        
                 int aquant=Integer.parseInt(quant.getText());
        int copie=Integer.parseInt(copies.getText());
           try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                 String sql = "update accessories set  Quantity = ? where id = ?";
                 PreparedStatement pstmt = conn.prepareStatement(sql);
            int val=copie-aquant;
            pstmt.setInt(1,val);
            
            pstmt.setInt(2,Integer.parseInt(a_id.getText()));
            
            pstmt.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Record Modified");
            conn.close();
  
            }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
               
              
            /* try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                String sql = "insert into bill values(?,?,?,?,?,?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(id.getText()));
                pstmt.setString(2,C_id.getText());
                 pstmt.setString(4,Expiry_date.getText());
               pstmt.setString(3,jTextField1.getText());
                pstmt.setString(5,ltotal.getText());
               pstmt.setString(6,quant.getText());
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted");
                conn.close();
            }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }*/
    }//GEN-LAST:event_jbtnaddActionPerformed

     void showDate()
    {
      Date d = new Date();
      SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
      Expiry_date.setText(s.format(d)); 
      
    }
    
    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        // TODO add your handling code here:
          this.hide();
        login_s frm=new login_s();
        frm.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtndisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndisplayActionPerformed
        // TODO add your handling code here:
         try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                String sql = "insert into bill values(?,?,?,?,?,?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(id.getText()));
                pstmt.setString(2,C_id.getText());
                 pstmt.setString(4,Expiry_date.getText());
               pstmt.setString(3,jTextField1.getText());
                pstmt.setString(5,ltotal.getText());
               pstmt.setString(6,tquant.getText());
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted");
                conn.close();
            }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
        this.setVisible(false); 
        new Billdisplay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtndisplayActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
         String PATTERN ="^[0-9]{0,3}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(id.getText());
        if(!match.matches()) {
            lid.setText("incorrect!");
            jbtnadd.setEnabled(false);
        }
        else
        {
          lid.setText(null); 
                      jbtnadd.setEnabled(true);

        }
    }//GEN-LAST:event_idKeyReleased

    private void C_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C_idKeyReleased
        // TODO add your handling code here:
        
        String PATTERN ="^[0-9 ]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(C_id.getText());
        if(!match.matches()) {
            lname.setText(" Incorrect!");
                        jbtnadd.setEnabled(false);

        }
        else
        {
          lname.setText(null); 
                      jbtnadd.setEnabled(true);

        }
        
        
    }//GEN-LAST:event_C_idKeyReleased
 



    private void jbtndisplayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtndisplayKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtndisplayKeyReleased
           
    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void pay_methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_methodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_methodActionPerformed

    private void pay_methodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pay_methodKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pay_methodKeyReleased

    private void quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantActionPerformed

      private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        int d,m,y;
     GregorianCalendar gc = new GregorianCalendar();
     d=gc.get(Calendar.DAY_OF_MONTH);
     m=gc.get(Calendar.MONDAY);
     y=gc.get(Calendar.YEAR);
    //System.out.print(d+(m+1)+y);
    image.setText(String.valueOf(y+"-"+(m+1)+"-"+d));

        try{
Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");

            String sql = "select max(id) from bill ";
PreparedStatement pstmt = conn.prepareStatement(sql);
            //pstmt.setInt(1,Integer.parseInt(isbn.getText()));

ResultSet rs = pstmt.executeQuery();
while(rs.next())
            {
int billno = rs.getInt(1)+1;
id.setText(Integer.toString(billno));

            }

conn.close();

}catch(ClassNotFoundException | SQLException e)
        { 
JOptionPane.showMessageDialog(null,e);
        }
    }                 
    
    private void a_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_idKeyReleased
        // TODO add your handling code here:
        
         String PATTERN ="^[0-9 ]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(a_id.getText());
        if(!match.matches()) {
            laid.setText(" Incorrect!");
            jbtnadd.setEnabled(false);
        }
        else
        {
          laid.setText(null); 
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
            String value=a_id.getText();
            String sql = "select Name,Amount,Quantity from accessories where id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            //String value=jComboBox1.getSelectedItem().toString();
            pstmt.setString(1,value);

            ResultSet rs = pstmt.executeQuery();

            if(rs.next())
            {
                aname.setText(rs.getString("Name"));
                amount.setText(rs.getString("Amount"));
                copies.setText(rs.getString("Quantity"));
                quant.setText("1");
            }
          conn.close();

        }catch(ClassNotFoundException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_a_idKeyReleased

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtActionPerformed

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
         int a=Integer.parseInt(quant.getText());
       int b=Integer.parseInt(copies.getText());
       
       if( a > b )
       {
           JOptionPane.showMessageDialog(null," Insufficient Quantity .");
           quant.setText(" ");
       }
        int one = Integer.parseInt(amount.getText());
                int two = Integer.parseInt(quant.getText());
                String ans = String.valueOf(one*two);
                amt.setText(ans);
        
    }//GEN-LAST:event_costActionPerformed

    private void Expiry_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Expiry_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Expiry_dateActionPerformed

    private void Expiry_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Expiry_dateKeyReleased
        // TODO add your handling code here:
         String PATTERN ="^[0-9]{4}-[0-9]{2}-[0-9]{2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(Expiry_date.getText());
        if(!match.matches()) {
            lexp.setText(" Incorrect!");
                        jbtnadd.setEnabled(false);

        }
        else
        {
          lexp.setText(null); 
                      jbtnadd.setEnabled(true);

        }
    }//GEN-LAST:event_Expiry_dateKeyReleased

    private void totallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totallActionPerformed
        // TODO add your handling code here:
         int total=0;
         for(int i=0;i<jTable1.getRowCount();i++)
         {
             int amount=Integer.parseInt((String) jTable1.getValueAt(i,4));
             total+=amount;
         }
         etotal.setText(String.valueOf(total));
          int ftotal=Integer.parseInt(etotal.getText());
         ltotal.setText(""+ftotal);
          
                int quant=0;
         for(int i=0;i<jTable1.getRowCount();i++)
         {
             int quantity=Integer.parseInt((String) jTable1.getValueAt(i,3));
             quant+=quantity;
         }
         qtotal.setText(String.valueOf(quant));
         int tquantity=Integer.parseInt(qtotal.getText());
         tquant.setText(""+tquantity);
                
         /*double quant=0;
         for(int i=0;i<jTable1.getRowCount();i++)
         {
             int quantity=Integer.parseInt((String) jTable1.getValueAt(i,3));
             quant+=quantity;
         }*/
        // qtotal.setText(String.valueOf(quant));
       
    }//GEN-LAST:event_totallActionPerformed

    private void ltotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ltotalActionPerformed

    private void a_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_idActionPerformed

    private void quantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantKeyReleased
        // TODO add your handling code here:
       /* int aquant=Integer.parseInt(quant.getText());
        int copie=Integer.parseInt(copies.getText());
           try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                 String sql = "update accessories set  Quantity = ? where id = ?";
                 PreparedStatement pstmt = conn.prepareStatement(sql);
            int val=copie-aquant;
            pstmt.setInt(1,val);
            
            pstmt.setInt(5,Integer.parseInt(a_id.getText()));
            
            pstmt.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Record Modified");
            conn.close();
  
            }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }*/
       
    }//GEN-LAST:event_quantKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_id;
    private javax.swing.JTextField Expiry_date;
    private javax.swing.JTextField a_id;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amt;
    private javax.swing.JLabel aname;
    private javax.swing.JLabel copies;
    private javax.swing.JButton cost;
    private javax.swing.JLabel etotal;
    private javax.swing.JTextField id;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTextField1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtndisplay;
    private javax.swing.JLabel laid;
    private javax.swing.JLabel lexp;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField ltotal;
    private javax.swing.JComboBox<String> pay_method;
    private javax.swing.JLabel qtotal;
    private javax.swing.JTextField quant;
    private javax.swing.JButton totall;
    private javax.swing.JLabel tquant;
    // End of variables declaration//GEN-END:variables
}
