/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compshop;

import java.awt.HeadlessException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
//import java.sql.SQLException;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Somnath
 */
public class Customer_details extends javax.swing.JFrame {

    /**
     * Creates new form Customer_details
     */
    public Customer_details() {
        initComponents();
        setTitle(" Bookstore  Management System-Customer Management");
        jbtndelete.setEnabled(false);
        jbtnmodify.setEnabled(false);

       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cphone = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        caddress = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        jbtndisplay = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jbtndelete = new javax.swing.JButton();
        jbtnmodify = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtnsearch = new javax.swing.JButton();
        lcid = new javax.swing.JLabel();
        lcname = new javax.swing.JLabel();
        laddr = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        lphoneno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        show_validation = new javax.swing.JLabel();

        setDefaultCloseOperation(0
        );
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Customer id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Customer Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 0, 500, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 230, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 230, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Phone no");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 390, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 300, 190, 40);

        cphone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cphoneMouseClicked(evt);
            }
        });
        cphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cphoneActionPerformed(evt);
            }
        });
        cphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cphoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cphoneKeyReleased(evt);
            }
        });
        jPanel1.add(cphone);
        cphone.setBounds(250, 390, 350, 40);

        cemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cemailMouseClicked(evt);
            }
        });
        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        cemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cemailKeyReleased(evt);
            }
        });
        jPanel1.add(cemail);
        cemail.setBounds(250, 300, 350, 40);

        caddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        caddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddressActionPerformed(evt);
            }
        });
        caddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caddressKeyReleased(evt);
            }
        });
        jPanel1.add(caddress);
        caddress.setBounds(250, 230, 340, 40);

        cname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel1.add(cname);
        cname.setBounds(250, 160, 340, 40);

        jbtndisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndisplay.setText("Display");
        jbtndisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndisplayActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndisplay);
        jbtndisplay.setBounds(620, 500, 110, 31);

        jbtnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnback.setText("Back");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback);
        jbtnback.setBounds(800, 500, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter 1-4 digit Customer Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 120, 180, 17);

        cid.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cidMouseClicked(evt);
            }
        });
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        cid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cidKeyReleased(evt);
            }
        });
        jPanel1.add(cid);
        cid.setBounds(250, 80, 340, 40);

        jbtndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndelete);
        jbtndelete.setBounds(450, 500, 100, 31);

        jbtnmodify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnmodify.setText("Modify");
        jbtnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodifyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmodify);
        jbtnmodify.setBounds(270, 500, 110, 31);

        jbtnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnadd.setText("Add");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnadd);
        jbtnadd.setBounds(110, 500, 90, 31);

        jbtnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsearch.setText("Search");
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsearch);
        jbtnsearch.setBounds(770, 110, 100, 40);

        lcid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lcid);
        lcid.setBounds(610, 110, 100, 40);

        lcname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lcname);
        lcname.setBounds(610, 180, 110, 40);

        laddr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(laddr);
        laddr.setBounds(610, 260, 100, 40);

        lemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lemail);
        lemail.setBounds(620, 340, 70, 40);

        lphoneno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lphoneno);
        lphoneno.setBounds(620, 430, 90, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ex:- 123@abc.com");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 340, 260, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Enter 10 digit mobile number.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 430, 290, 30);

        show_validation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show_validation.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pruthviraj Deshmukh\\Desktop\\Software\\Computer Shopee\\src\\images\\customer-service-1433639_1920-1080x675.png")); // NOI18N
        jPanel1.add(show_validation);
        show_validation.setBounds(0, 0, 940, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cphoneActionPerformed
        // TODO add your handling code here:
      
        
    
    }//GEN-LAST:event_cphoneActionPerformed
        
    private void jbtnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodifyActionPerformed
        // TOhDO add your handling code here:
                jbtnadd.setEnabled(false);
        jbtndelete.setEnabled(false);
        jbtndisplay.setEnabled(true);

           try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                 String sql = "update customer set  cust_name = ?, Emai_id = ?, phone_no = ?, address = ? where c_id = ?";
                 PreparedStatement pstmt = conn.prepareStatement(sql);
            
            pstmt.setString(1, cname.getText());
            
            pstmt.setString(2, cemail.getText());
            pstmt.setString(3, cphone.getText());
            pstmt.setString(4, caddress.getText());
            pstmt.setInt(5,Integer.parseInt(cid.getText()));
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Modified");
            conn.close();
  
            }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
       
        
     
    }//GEN-LAST:event_jbtnmodifyActionPerformed

    private void jbtndisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndisplayActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        new custdispaly().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtndisplayActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        // TODO add your handling code here:
         this.hide();
        login_s frm=new login_s();
        frm.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void cidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(cid.getText());
        if(!match.matches()) {
            lcid.setText("incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
          lcid.setText(null);
          jbtnadd.setEnabled(true);
          //jbtnmodify.setEnabled(true);
        }
       
    }//GEN-LAST:event_cidKeyReleased

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        // TODO add your handling code here:
         jbtndelete.setEnabled(false);  
   jbtnmodify.setEnabled(false);
      
           
        String Customerid=cid.getText();
          String Name=cname.getText();
           
            String Email=cemail.getText();
             String PhoneNo=cphone.getText();
              String Address=caddress.getText();
              
               if(Customerid.equals("")){
                   JOptionPane.showMessageDialog(null," Customer id is Mandatory .");
               }
                if(Name.equals("")){
                   JOptionPane.showMessageDialog(null," Customer name is Mandatory .");
                }
                   
             if(Email.equals("")){
                   JOptionPane.showMessageDialog(null," Customer email is Mandatory .");
             }
               if(PhoneNo.equals("")){
                   JOptionPane.showMessageDialog(null," Customer phone number is Mandatory .");
               }
               
               if(Address.equals("")){
                   JOptionPane.showMessageDialog(null," Customer address is Mandatory .");
                }
               
             try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                String sql = "insert into customer(c_id,cust_name,address,Emai_id,phone_no) values('"+Customerid+"','"+Name+"','"+Address+"','"+Email+"','"+PhoneNo+"')";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                /*pstmt.setInt(1,Integer.parseInt(cid.getText()));
                pstmt.setString(2,cname.getText());
                pstmt.setString(3, cemail.getText());
                pstmt.setString(4,cphone.getText());
                pstmt.setString(5,caddress.getText());*/
                
                pstmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Inserted");
                conn.close();
            }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void cphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cphoneKeyPressed
           
    }//GEN-LAST:event_cphoneKeyPressed

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased
        // TODO add your handling code here:
      String PATTERN ="^[a-zA-Z ]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(cname.getText());
        if(!match.matches()) {
            lcname.setText(" Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
          lcname.setText(null);
          jbtnadd.setEnabled(true);
          //jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void cemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cemailKeyReleased
        // TODO add your handling code here:
        //email@gmail.com
        String PATTERN ="^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(cemail.getText());
        if(!match.matches()) {
            lemail.setText(" Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
          lemail.setText(null); 
          jbtnadd.setEnabled(true);
          //jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_cemailKeyReleased

    private void cphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cphoneKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(cphone.getText());
        if(!match.matches()) {
            lphoneno.setText("Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
          lphoneno.setText(null); 
          jbtnadd.setEnabled(true);
         // jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_cphoneKeyReleased

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void caddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caddressKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z0-9/,.''-]{0,50}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(caddress.getText());
        if(!match.matches()) {
            laddr.setText(" Incorrect!");
            jbtnadd.setEnabled(false);
            jbtnmodify.setEnabled(false);
        }
        else
        {
          laddr.setText(null);
          jbtnadd.setEnabled(true);
         // jbtnmodify.setEnabled(true);
        }
    }//GEN-LAST:event_caddressKeyReleased

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        jbtndisplay.setEnabled(true);
        jbtnadd.setEnabled(false);
jbtndelete.setEnabled(true);
        jbtnmodify.setEnabled(true);

             try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                     String sql = "select * from customer where c_id = ?";
                     PreparedStatement pstmt = conn.prepareStatement(sql);
                     pstmt.setInt(1,Integer.parseInt(cid.getText()));
                     
                     ResultSet rs = pstmt.executeQuery();
                     if(rs.next())
                     {   
                         cid.setText(rs.getString("c_id"));
                         cname.setText(rs.getString("cust_name"));
                         cemail.setText(rs.getString("Emai_id"));
                         cphone.setText(rs.getString("phone_no"));
                         caddress.setText(rs.getString("address"));
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(null," Record not found");
                     }
                     conn.close();
            
        }catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnsearchActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        // TODO add your handling code here:
jbtnadd.setEnabled(false);
        jbtnmodify.setEnabled(false);
        jbtndisplay.setEnabled(true);
               
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/csms?zeroDateTimeBehavior=convertToNull","root","");
                String sql = "delete from customer where c_id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(cid.getText()));
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Deleted Succesfully");
                cid.setText("");
                cname.setText("");
                cemail.setText("");
                cphone.setText("");
                caddress.setText("");
                 conn.close();
           }
        catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        { 
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void caddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddressActionPerformed

    private void cidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cidKeyPressed

    private void cidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cidMouseClicked
        // TODO add your handling code he
    }//GEN-LAST:event_cidMouseClicked

    private void cemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cemailMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_cemailMouseClicked

    private void cphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cphoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cphoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Customer_details().setVisible(true);
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private static javax.swing.JTextField cphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtndisplay;
    private javax.swing.JButton jbtnmodify;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JLabel laddr;
    private javax.swing.JLabel lcid;
    private javax.swing.JLabel lcname;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lphoneno;
    private javax.swing.JLabel show_validation;
    // End of variables declaration//GEN-END:variables
}
