/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compshop;


/**
 *
 * @author Somnath
 */
public class login_s extends javax.swing.JFrame {

    /**
     * Creates new form login_s
     */
    public login_s() {
        initComponents();
        setTitle("Computer Shopee Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnbooks = new javax.swing.JButton();
        jbtndetails = new javax.swing.JButton();
        jbtnout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(567, 426));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("   MENU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 0, 300, 120);

        jbtnbooks.setBackground(new java.awt.Color(255, 255, 255));
        jbtnbooks.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnbooks.setForeground(new java.awt.Color(153, 0, 51));
        jbtnbooks.setText("Accessories");
        jbtnbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbooksActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbooks);
        jbtnbooks.setBounds(370, 250, 360, 70);

        jbtndetails.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtndetails.setForeground(new java.awt.Color(153, 0, 51));
        jbtndetails.setText("Customer Details");
        jbtndetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndetailsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndetails);
        jbtndetails.setBounds(370, 140, 360, 70);

        jbtnout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnout.setForeground(new java.awt.Color(153, 0, 51));
        jbtnout.setText("LogOut");
        jbtnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnout);
        jbtnout.setBounds(770, 460, 160, 70);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 51));
        jButton1.setText("Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 360, 360, 70);

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pruthviraj Deshmukh\\Desktop\\Software\\Computer Shopee\\src\\images\\ur2l.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(940, 600));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        this.setVisible(false);
        new Bill().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoutActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jbtnoutActionPerformed

    private void jbtndetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndetailsActionPerformed

        this.setVisible(false);
        new Customer_details().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbtndetailsActionPerformed

    private void jbtnbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbooksActionPerformed
        this.setVisible(false);
        new Accessories().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtnbooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_s().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnbooks;
    private javax.swing.JButton jbtndetails;
    private javax.swing.JButton jbtnout;
    // End of variables declaration//GEN-END:variables
}
